### ISSUE TITLE
Avatars are not resized on phpBB 3.3.5

### ISSUE THREAD

**Issue by Abbotta4** [GerB/avatarresize#2]
I am using phpBB 3.3.5 and imagemagick module version 3.5.1. I have successfully enabled the extension, but when I upload an avatar to an account, I get the same warning as one would get without the extension:
`The submitted avatar is 1280 pixels wide and 721 pixels high. Avatars must be at least 20 pixels wide and 20 pixels high, but no larger than 171 pixels wide and 230 pixels high.`

**Comment by GerB** [comment]
Please report with details here: https://www.phpbb.com/community/viewtopic.php?f=456&t=2459751
